image: registry.safone.ltd:1443/cqsafone/maven:3.6.3-openjdk-17

variables:
  MAVEN_CLI_OPTS: " -s .m2/settings.xml --batch-mode -P gitlab-runner"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dmaven.test.skip=true"

stages:
  - build


build:
  stage: build
  tags:
    - k8s-runner-dev
  script:
    - mvn clean deploy -U $MAVEN_CLI_OPTS

