
spring:
  security:
    oauth2:
      client:
        registration:
          default:
            client-id: password-client-id
            client-name: password-client-name
            client-secret: secret3
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - openid
#              - message.read
            redirect-uri: "http://127.0.0.1:8080/{action}/oauth2/code/{registrationId}"
        provider:
          default:
            issuer-uri: http://127.0.0.1:9000
  redis:
    host: 192.168.0.210
    port: 16379
    database: 4
  profiles:
    active: jpa
lightning:
  security:
    app:
      auth:
        server:
          config:
            no-separation:
              enable-saved-request-forward: false
              enable-forward: false
              failure-forward-or-redirect-url: /login-failure.html
              # because central auth server host == current app auth server ..., need modify ..
              token-identifier: APPJSESSIONID
            backend-separation:
              login-success-message: "登陆成功了,亲!!!"
              login-failure-message: "登陆失败了,亲!!!"
            separation: false
            # oauth 相关配置 ...
            oauth2:
              login:
                config:
                  # client registration store ..  need introduction  jpa dependencies
                  client-registration-store-kind: jpa

server:
  port: 8080