lightning:
  security:
    app:
      auth:
        server:
          config:
            server-meta-data-endpoint-config:
              enable-oidc: false
            backend-separation:
              login-success-message: "登陆成功了呀，亲!"
              login-failure-message: "登陆失败了呀，亲!"
              bad-credential-message: "请检查账户密码呀，亲!"
              enable-account-status-details: true
              un-authenticated-message: 未登录,请登录!!
            no-separation:
              enable-saved-request-forward: true
              default-success-url: /login.html
            separation: true
            authorization-store-config:
              store-kind: jpa
server:
  port: 8081

spring:
  security:
    user:
      password: 123456
      roles:
        - role1
        - role2
        - role3
