lightning:
  auth:
    app:
      server:
        config:
          specification:
            authentication-token-setting:
              enable: false
        form:
          login:
            config:
              # 让它不需要 LightningAuthenticationService ...
              is-separation: false