lightning:
  auth:
    app:
      server:
        form:
          login:
            config:
              is-separation: true
  security:
    resource:
      server:
        permission:
          url-white-list:
            - /**

spring:
  security:
    user:
      password: 123456
