server:
  port: 9090
lightning:
  security:
    oauth2:
      resource:
        server:
          opaque-token-config:
            client-id: password-client-id
            client-secret: secret3
            introspect-token-endpoint-url: http://127.0.0.1:9000/auth/v1/oauth2/introspect
            client-methods:
              - client_secret_basic
              - client_secret_post
    resource:
      server:
        token-verification-config:
          token-type: opaque
